file_name: './donnees/donnees_climatiques.csv'
specimen: 'fieldNumber' #"Please enter the name of the column containing the specimens names: "
names: ['Lat_start_dec', 'Lat_end_dec', 'Long_start_dec', 'Long_end_dec', 'depth_start', 'depth_end','windspeed_start','windspeed_end','watertemp_ground','O2-saturation_ground','fieldNumber']
bootstrap_threshold: 100
dist_threshold: 10
window_size: 10
step_size: 1
bootstrap_amount: 10000 #The number of bootstrap samples to generate.
data_names: ['Lat_start_dec_newick', 'Lat_end_dec_newick', 'Long_start_dec_newick', 'Long_end_dec_newick', 'depth_start_newick','depth_end_dec_newick','windspeed_start_newick','windspeed_end_newick','watertemp_ground_newick','O2-saturation_ground_newick']
reference_gene_dir: './donnees'
reference_gene_file: 'fasta2.fas'
makeDebugFiles: True
alignment_method: '2' #Please select one ~ 0:no alignment, 1:pairwiseAligner, 2:MUSCLE, 3:CLUSTALW, 4:MAFFT
distance_method: '0' #Please select one  ~ 0: All distance methods, 1: Least-Square distance, 2: Robinson-Foulds distance, 3: Euclidean distance (DendroPY)
fit_method: '1' #Please select one ~ 1:Wider Fit by elongating with Gap (starAlignment), 2:Narrow-fit prevent elongation with gap when possible
tree_type: '1' #Please select one ~ 1: BioPython consensus tree, 2: FastTree application
rate_similarity: 75
method_similarity: '2' #Please select one :
    # 1: Hamming distance
    # 2: Levenshtein distance
    # 3: Damerau-Levenshtein distance
    # 4: Jaro similarity
    # 5: Jaro-Winkler similarity
    # 6: Smith–Waterman similarity
    # 7: Jaccard similarity
    # 8: Sørensen-Dice similarity
